# -*- coding: utf-8 -*-
"""CodeAlpha_Task_Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OspwIfjX7BMoI9POdQTDu1_IuO_wykCN
"""

import os

#Colab doesn't automatically have a folder called MyFolder.
#So we need to create a test folder first.

# Create a test folder
os.makedirs("MyFolder", exist_ok=True)

# Create some sample files
open("MyFolder/photo1.jpg", "w").close()
open("MyFolder/photo2.jpg", "w").close()
open("MyFolder/document.txt", "w").close()
open("MyFolder/notes.pdf", "w").close()

print("Test files created.")

import os
import shutil

# Folder containing the files
source_folder = "MyFolder"

# Folder where JPG files will be moved
destination_folder = "MyFolder/JPG_Files"

# Create destination folder if it does not exist
if not os.path.exists(destination_folder):
    os.makedirs(destination_folder)

# Check all files in the source folder
for file in os.listdir(source_folder):

    # Check if the file is a JPG file
    if file.lower().endswith((".jpg", ".jpeg")):

        source_path = os.path.join(source_folder, file)
        destination_path = os.path.join(destination_folder, file)

        # Move the JPG file
        shutil.move(source_path, destination_path)

        print(file, "moved successfully.")

print("\nJPG file organization completed!")

import os

print(os.listdir("MyFolder"))
print(os.listdir("MyFolder/JPG_Files"))

